name: Vercel Preview (PR)

on:
  pull_request:
    branches: [ "**" ]

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with: { fetch-depth: 0 }

    - uses: actions/setup-node@v4
      with: { node-version: 18 }

    - run: npm i -g vercel@latest
      name: Install Vercel CLI

    - run: |
        npm ci
        npm run build
      name: Install deps & build

    - name: Deploy Preview
      env:
        VERCEL_TOKEN:      ${{ secrets.VERCEL_TOKEN }}
        VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
      run: |
        vercel deploy \
          --prod=false \
          --yes \
          --token "$VERCEL_TOKEN"
