name: Vercel Preview (PR)

on:
  pull_request:
    branches: [ "**" ]

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install Vercel CLI
      run: npm i -g vercel@latest

    - name: Install deps & build
      run: |
        npm ci
        npm run build        # next build

    - name: Deploy Preview
      env:
        VERCEL_TOKEN:      ${{ secrets.VERCEL_TOKEN }}      # אסימון אישי (Personal Token)
        VERCEL_ORG_ID:     ${{ secrets.VERCEL_ORG_ID }}     # team_xxx (Team ID)
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }} # prj_xxx (Project ID)
      run: |
        vercel deploy \
          --prod=false \
          --yes \
          --token "$VERCEL_TOKEN"
